### ISSUE TITLE
没搞明白怎么运行这个项目后，怎样看所有封装后的功能对应的例子

### ISSUE THREAD

**Issue by mengnaYi** [alibaba/dawn#106]
没搞明白怎么运行这个项目后就能看所有的封装后的对应的例子吗

**Comment by Houfeng** [comment]
通过 `npm i dawn -g` 安装后（也可以用 cnpm），就可以通过 `dn init` 创建项目，体验一些基础示例工程了。

**Comment by mengnaYi** [comment]
一开始下载时就按照下面备注提示的这个步骤运行了命令，但是也没自启动哪个项目呀，是还需要自己创建吗？后来又百度了别的方法，结果是可以自启动一个自己想看的template,但是对应的vue或react框架（就是packages文件夹下dn-template-react或dn-template-vue文件）的index.js中import React from 'react';这句变红报错，这是导入出问题嘛？

**Comment by mengnaYi** [comment]
https://zhuanlan.zhihu.com/p/28397857看的这个链接执行的

**Comment by Houfeng** [comment]
按如下步骤，就能创建一个工程，并启动它

```sh
# 1. 创建 & 初始化
$ dn init -t front

# 2. 开发 & 实时编译
$ dn dev

# 3. 语法检查 & 测试
$ dn test

# 4. 构建 & 打包
$ dn build
```

**Comment by mengnaYi** [comment]
![e4f99c06-3a98-4557-b665-fe2d2a2bccdf](https://user-images.githubusercontent.com/32327613/34025903-756856dc-e18d-11e7-85b8-e72fb8194a85.png)
还差点，就是报错，我执行是这样的：
重新下载一份项目重新启动开始
$npm i dawn -g
$ dn init -t front
$ dn dev
$ dn test
$ dn build
-----------------这些执行后没弹窗
然后又写了下
$ dn init template --force
(这时选的vue那个template)
$ dn dev 
然后就自动弹出上面那个页面，然后检查后报错。。

**Comment by xdlrt** [comment]
项目目录下执行 `npm i` 后重试，目前看起来是依赖模块没有安装。

**Comment by mengnaYi** [comment]
@xdlrt 可以了 ，谢谢
@Houfeng ，谢谢
