### ISSUE TITLE
ubuntu lts 16 虚拟机无法删除dawn

### ISSUE THREAD

**Issue by chenhaihong** [alibaba/dawn#126]
# 无法删除dawn
dawn@0.11.0， npm@5.6.0
执行rm，一直在load依赖关系，没法删除。

**Comment by Houfeng** [comment]
没出现过类似的问题，稍候找个一样的环境试一下，再来回复你。

**Comment by chenhaihong** [comment]
应该是我的电脑硬盘有问题导致的。
