### ISSUE TITLE
如何配置webpack跨域proxy？

### ISSUE THREAD

**Issue by zxj963577494** [alibaba/dawn#131]
### 1. Information

OS & version | Node version | Dawn version
------------ | -------------| ---------------
your-version | your-version | your-version 

#### pipe.yml
![_20180326144622](https://user-images.githubusercontent.com/6766515/37891696-cb26eefc-3107-11e8-8202-e82504ac264c.png)

#### wp.conf.js
![_20180326150919](https://user-images.githubusercontent.com/6766515/37891701-ce0eb276-3107-11e8-8b7b-f1398f09b102.png)

提示 “/get” Not Found (404)
### 3. Recurrence

The steps of problem recurrence

**Comment by GuoChen-WHU** [comment]
dawn 并没有使用 webpack-dev-server 作为开发服务器，所以这样配置是不行的。
使用 dawn 创建的项目，在项目根目录会有一个 server.yml 配置文件，在里面配置代理就可以了，比如：
```yml
proxy:
    rules: 
      ^/api(.*): 'https://www.aliyun.com/'
```
会将所有对 /api/xxx 的请求代理到 https://www.aliyun.com/
