### ISSUE TITLE
dawn 0.12.0 这个版本，不支持模块热更新，   以及不支持 浏览器自动刷新。。。。。。请问如何解决，。。。。。。。这是我提的第三个此类问题，但是一直没人回答。

### ISSUE THREAD

**Issue by martinwithyou** [alibaba/dawn#133]
### 1. Information

OS & version | Node version | Dawn version
------------ | -------------| ---------------
your-version | your-version | your-version 

### 2. Problem

Describe your problems in as much detail as possible

### 3. Recurrence

The steps of problem recurrence

**Comment by xdlrt** [comment]
查看pipe.yml，可以这样写，

dev:
  - name: server
    port: 8080
    autoOpen: false
  - name: browser-sync

浏览器的自动刷新是由中间件提供的能力，不是dawn本身的能力。
