### ISSUE TITLE
请问dawn运行的时候 很卡怎么处理?我的代码直接卡的不能写了,用dva是正常的,

### ISSUE THREAD

**Issue by kaykie** [alibaba/dawn#135]
### 1. Information

OS & version | Node version | Dawn version
------------ | -------------| ---------------
your-version | your-version | your-version 

0.12.0
### 2. Problem

Describe your problems in as much detail as possible
请问dawn运行的时候 很卡怎么处理?我的代码直接卡的不能写了,用dva是正常的,不会卡,可顺了.
可以做哪些方面的优化

### 3. Recurrence

The steps of problem recurrence
直接运行 dn dev

**Comment by xdlrt** [comment]
可以再详细的描述下问题吗？操作系统？是指watch过程中编译时间长吗？是否排除了 node_modules文件夹？

**Comment by kaykie** [comment]
用的mac,编辑器用的webstrome,在编译启动以及build的时候,直接卡了不能动,node_modules已经exclu,在使用dn d的时候尤其卡.
