### ISSUE TITLE
Server中间件文档描述错误

### ISSUE THREAD

**Issue by naifen00** [alibaba/dawn#146]
### 1. Information

OS & version | Node version | Dawn version
------------ | -------------| ---------------
macOS 10.13.5  | v8.11.1 | 0.12.1

### 2. Problem
https://alibaba.github.io/dawn/docs/#!/zh/middleware/dev-server
配置代理部分
```
请求到 /api/xxx 现在会被代理到请求 https://www.aliyun.com/api/xxx
```
应该改为
```
请求到 /api/xxx 现在会被代理到请求 https://www.aliyun.com/xxx
```
参照 [https://github.com/nokitjs/nokit-filter-proxy/blob/master/README.md](https://github.com/nokitjs/nokit-filter-proxy/blob/master/README.md)
### 3. Recurrence

无

**Comment by Houfeng** [comment]
没有错误

如下配置
```yaml
  rules: 
    ^/api(.*): 'https://www.aliyun.com/'
```

请求到 /api/xxx 会被代理到请求 https://www.aliyun.com/xxx

而如下配置

如下配置
```yaml
  rules: 
    ^/api/xxx: 'https://www.aliyun.com/'
```

请求到 /api/xxx 才会被代理到请求 https://www.aliyun.com/api/xxx

**Comment by naifen00** [comment]
文档现在是改对了的
