### ISSUE TITLE
文档不修复了吗, 这项目目前就一个维护？0.0

### ISSUE THREAD

**Issue by xbcc123** [alibaba/dawn#188]
### 1. Information

OS & version | Node version | Dawn version
------------ | -------------| ---------------
your-version | your-version | your-version 

### 2. Problem

Describe your problems in as much detail as possible

### 3. Recurrence

The steps of problem recurrence

**Comment by Houfeng** [comment]
稍等

**Comment by Houfeng** [comment]
https://github.com/alibaba/dawn/pull/189
