### ISSUE TITLE
了解一下为什么node版本必须是v7以上

### ISSUE THREAD

**Issue by henryzp** [alibaba/dawn#2]
我本地装的node是v6.11.x，即LTS的版本。。

然后要跑这个工具，必须用nvm。。

想了解的是，只是生成模板代码用到了v7，跑代码（即服务启动，打包）不需要v7，还是说都要v7？

**Comment by Houfeng** [comment]
@henryzp 
工具 cli 本身目前要求 7.6+，
由模板创建的工程代码，并不限定，取决于构建配置。
