### ISSUE TITLE
lint相关规则实际使用调优建议

### ISSUE THREAD

**Issue by soulwu** [alibaba/dawn#224]
1. 建议把`__html`加入到`@typescript-eslint/naming-convention`的例外中
![image](https://user-images.githubusercontent.com/1633638/87400644-aab20000-c5eb-11ea-9ebc-8e1f57474c9b.png)

2. `react/prop-types`规则建议关闭，目前这条规则无法识别TS中SFC类型定义
![image](https://user-images.githubusercontent.com/1633638/87400973-1bf1b300-c5ec-11ea-8717-77bd7fd3f1a4.png)

**Comment by jeasonstudio** [comment]
1. `@typescript-eslint/naming-convention` 的规则配置非常复杂，需要具体梳理下，并 case by case 的做适配，后面我来具体跟进。
2. `react/prop-types` 将在下个小迭代关闭，这个规则反馈非常多，目前看也不合理。cc @xdlrt

**Comment by jeasonstudio** [comment]
+ `max-lines-per-function`：Functional Component 大环境下限制单函数行数也不合理，会导致编辑器大面积报黄，考虑 `off` 或改成 `max-statements`
