### ISSUE TITLE
init 不成功

### ISSUE THREAD

**Issue by sarike** [alibaba/dawn#23]
看到了 dawn 的介绍，想试用一下，结果没有 init 成功。
![image](https://user-images.githubusercontent.com/1788906/30193341-1c180862-947f-11e7-980f-a5cd02186297.png)

dawn 版本：`0.6.1`

我的 node 版本：`v8.2.1`，npm: `5.3.0`

**Comment by Houfeng** [comment]
应该是执行过程中强制中止，意外导致缓存文件不完整了，执行一下 dn update， 再重试

**Comment by agileago** [comment]
同上，并且init的时候特别漫长所以才会终止命令，然后再init就会报错，已经用了淘宝源了

**Comment by Houfeng** [comment]
@agileago 
还是有错误吗？执行一下 `DN_DEBUG=true dn init` 把打印的信息，能否贴过来。

**Comment by Houfeng** [comment]
@agileago @sarike 
尽快会改进一下，在意外被中止时减少此情况的发生。

**Comment by sarike** [comment]
我 dn update 后再执行就没问题了。

建议：

init 的时候最好不要一直显示 init template... 在那不动，这个过程有点久，我以为 hang 死了，所以就中止了。

如果有个进度条或者有加载 modules 的控制台输出的话会好点。

**Comment by agileago** [comment]
![image](https://user-images.githubusercontent.com/11799110/30200485-b96e1d66-94a9-11e7-9e65-434a987c5c1d.png)
没有debug信息，还是很慢，还没Init成功

**Comment by agileago** [comment]
![image](https://user-images.githubusercontent.com/11799110/30200606-3d6f49f0-94aa-11e7-970b-0064cc7bc054.png)
成功了，不过我感觉是等了至少5分钟，我的网络应该没什么问题，装其他包都是秒装

**Comment by Houfeng** [comment]
@sarike @agileago 
已发布 0.6.2，默认源调整为 `https://registry.npm.taobao.org` 了，
后续还会有持续改进。
