### ISSUE TITLE
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (1605870103558)

### ISSUE THREAD

**Issue by zhenizhui** [alibaba/dawn#234]
### 1. Information

| OS & version | Node version | Dawn version |
| ------------ | ------------ | ------------ |
| win10 | v14.8.0 | 1.9.0 |

### 2. Problem

when i run `dn init`, and then it was wrong.

运行`dn init`，然后就报错了。

### 3. Recurrence

The steps of problem recurrence

```
> npm install dawn -g

> mkdir demo-dn

> cd demo-dn

> dn init

[19:01:43] The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. 
Received type number (1605870103558)
```

**Comment by jeasonstudio** [comment]
@zhenizhui 暂时将 Nodejs 版本降到 v10-v12，这个问题近期会修复
