### ISSUE TITLE
dn init 不成功

### ISSUE THREAD

**Issue by DevilXu** [alibaba/dawn#24]
dn init的时候一直再init template中，debug显示如下信息：
{ Error: unexpected end of file
    at Gunzip.zlibOnError (zlib.js:152:15)
 errno: -5, code: 'Z_BUF_ERROR' }

![image](https://user-images.githubusercontent.com/6022152/30200724-ae93996a-94aa-11e7-99b8-0c3458d10228.png)

**Comment by Houfeng** [comment]
dn update 可以再试试

**Comment by DevilXu** [comment]
可以了，就是时间有点长

**Comment by Houfeng** [comment]
https://github.com/alibaba/dawn/issues/23
