### ISSUE TITLE
Node工程模板是做什么的？

### ISSUE THREAD

**Issue by zsea** [alibaba/dawn#60]
能否将Node8的特性编译到Node4环境？

**Comment by Houfeng** [comment]
Node 模板是一个最基础的模板，在 Dawn 开发之初，手动写了第一个「Node 模板」，可谓之「创始模板」。

基于这个模板创建了「中间件模板」，又基于「中间件模板」创建了各个「中间件」，然后，基于这个「Node 模板」和几个「中间件」创建了「前端工程模板」，进而创建了诸如 React/Vue 模板，还有我们厂内和业务贴合的各个「业务工程模板」。

Dawn 本身在某个版本，也基于了这个创始模板，Dawn 是基于自已进行的「单元测试」和「文档生成」

这个模板，没有太多配置，可以在这个模板中随意添加编译或其它配置。
