### ISSUE TITLE
安装失败   

### ISSUE THREAD

**Issue by wunayou** [alibaba/dawn#62]
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\.
.\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp: deps\winpty\winpty.gyp not found (cwd: C:\Users\Administrator\AppData\Roaming\npm\node_modules\dawn\node_modules\pty.js) while loading dependencies of binding.gyp while trying to lo
ad binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Roaming\npm\node_modules\dawn\node_modules\pty.js
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pty.js@0.3.1 (node_modules\dawn\node_modules\pty.js):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pty.js@0.3.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by Houfeng** [comment]
目前有一个可选依赖，在 windows 会有错误日志，但还是能成功安装并能正常使用的，此可先依赖稍后或会移除。
