### ISSUE TITLE
配置中心服务出错

### ISSUE THREAD

**Issue by hooper-hc** [alibaba/dawn#71]
![image](https://user-images.githubusercontent.com/11420374/31982266-92c428a2-b91d-11e7-8d5d-0ea3ea0c022d.png)

配置中心服务出错
我配置了自己的 tmplate.yml .在之行 tmplate 是出错了. 如上图, 请问什么问题? 

tmplate 路径: 

https://github.com/ofo-hooper/ofo-dawn/blob/master/template.yml

**Comment by hooper-hc** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/Users/echo/.nvm/versions/node/v8.7.0/bin/node',
1 verbose cli   '/Users/echo/.nvm/versions/node/v8.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dntest' ]
2 info using npm@5.4.2
3 info using node@v8.7.0
4 verbose run-script [ 'predntest', 'dntest', 'postdntest' ]
5 info lifecycle dawn@0.7.9~predntest: dawn@0.7.9
6 info lifecycle dawn@0.7.9~dntest: dawn@0.7.9
7 verbose lifecycle dawn@0.7.9~dntest: unsafe-perm in lifecycle true
8 verbose lifecycle dawn@0.7.9~dntest: PATH: /Users/echo/.nvm/versions/node/v8.7.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/echo/hooper/ofo/open-source/dawn/node_modules/.bin:/Users/echo/.nvm/versions/node/v8.7.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle dawn@0.7.9~dntest: CWD: /Users/echo/hooper/ofo/open-source/dawn
10 silly lifecycle dawn@0.7.9~dntest: Args: [ '-c', 'node ./bin/cli.js test' ]
11 silly lifecycle dawn@0.7.9~dntest: Returned: code: 1  signal: null
12 info lifecycle dawn@0.7.9~dntest: Failed to exec dntest script
13 verbose stack Error: dawn@0.7.9 dntest: `node ./bin/cli.js test`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/echo/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/echo/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid dawn@0.7.9
15 verbose cwd /Users/echo/hooper/ofo/open-source/dawn
16 verbose Darwin 16.7.0
17 verbose argv "/Users/echo/.nvm/versions/node/v8.7.0/bin/node" "/Users/echo/.nvm/versions/node/v8.7.0/bin/npm" "run" "dntest"
18 verbose node v8.7.0
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error dawn@0.7.9 dntest: `node ./bin/cli.js test`
22 error Exit status 1
23 error Failed at the dawn@0.7.9 dntest script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Houfeng** [comment]
应该是 github 的 url 的问题，blob 是对应页面，而不是对应的 yml 文件

**Comment by Houfeng** [comment]
通过 dn config 把 server 配置为 https://raw.githubusercontent.com/ofo-hooper/ofo-dawn/master 试试

**Comment by hooper-hc** [comment]
解决, 赞一个
