### ISSUE TITLE
这个项目特色是什么?

### ISSUE THREAD

**Issue by fantasthu** [alibaba/dawn#73]
目前有基础架构都很成熟了,但是我从本github中看不出这个项目的特色,或者说优势在哪?

**Comment by Houfeng** [comment]
@fantasthu 
README: [https://github.com/alibaba/dawn/blob/master/README-zh.md](https://github.com/alibaba/dawn/blob/master/README-zh.md)
文档: [https://alibaba.github.io/dawn/docs/](https://alibaba.github.io/dawn/docs/)

文档我们会及时完善和更新。

**Comment by xdlrt** [comment]
@fantasthu 这个项目对开发环境和生产环境进行封装，可以节省你在基础架构上的精力，同时配置很灵活，方便团队统一开发管理。新的项目可以尝试使用，任何问题都可以直接通过issue的方式沟通。
