### ISSUE TITLE
有没有vue的模板？

### ISSUE THREAD

**Issue by wlx200510** [alibaba/dawn#74]
如果已经打算后期支持，那我就不准备着手开发了

**Comment by Houfeng** [comment]
@wlx200510 
目前有一个简单 vue 模板，执行 `dn init` 就能看到列表，看看能否满足你的需要
如果有问题，可以直接在 issues 中反馈，或发起 PR。

**Comment by wlx200510** [comment]
单页面还是多页面的？

**Comment by Houfeng** [comment]
@wlx200510 
多页面的，当然也支持单页面，「单页」是「多页」的一种嘛
不过，默认只有一个 index 页，在 src 中直接添加新的「入口」文件自然就是多页了。
